### ISSUE TITLE
Sequence contains no elements Exception When Read DG > 2

### ISSUE THREAD

**Issue by htbtran9x** [giokoguashvili/MRTD.NET#6]
Hi giokoguashvili,
the function berTlvFirstByte() in Tag class has throw exception when i read DG 7 or DG11 or DG12, it execute Bytes() of SecureMessagingPipe step 
it nothing happen and read data success in DG1 and DG2 
what im missing?

**Comment by giokoguashvili** [comment]
Hi @htbtran9x, because it was implemented for demonstration purposes, I wrote it only for this instance. The main information is stored in these DGs

**Comment by htbtran9x** [comment]
Hi, i solved a problem, bcs the card only support list DG in tag response, and in tag has no DG 11 12 7. tks your ans.
